import type { TypographyProps } from '../Typography';
import type { HeadingProps } from './Heading';
export declare const RegularFontWeight: import("styled-components").FlattenInterpolation<import("styled-components").ThemeProps<import("styled-components").DefaultTheme>>;
export declare const BoldFontWeight: import("styled-components").FlattenInterpolation<import("styled-components").ThemeProps<import("styled-components").DefaultTheme>>;
export declare const HeadingBase: import("styled-components").FlattenInterpolation<import("styled-components").ThemedStyledProps<HeadingProps & TypographyProps, import("styled-components").DefaultTheme>>;
export declare const H1: any;
export declare const H2: any;
export declare const H3: any;
export declare const H4: any;
export declare const H5: any;
export declare const H6: any;
